apiVersion: extensions/v1
kind: Deployment
metadata:
  name: thequoter-canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thequoter
    spec:
      containers:
      - name: agileqc
        image: pastjean/agileqc:v1
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 20